import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const {
            mode = "local",
            anthropicApiKey = "",
            openaiApiKey = "",
            gatewayToken,
            instanceUrl = "http://localhost:3284",
            channels = {},
            ansible = null,
        } = body;

        // Generate a secure default token if not provided
        const token = gatewayToken || "<run: openssl rand -hex 32>";

        // ── .env file content ──────────────────────────────────────────────────
        const envLines = [
            "# OpenClaw Configuration — generated by ClawBot Skill Builder",
            `# Generated: ${new Date().toISOString()}`,
            "",
            "# Gateway auth",
            `OPENCLAW_GATEWAY_TOKEN=${token}`,
            "",
            "# Model provider API keys (set at least one)",
            anthropicApiKey
                ? `ANTHROPIC_API_KEY=${anthropicApiKey}`
                : "# ANTHROPIC_API_KEY=sk-ant-...",
            openaiApiKey ? `OPENAI_API_KEY=${openaiApiKey}` : "# OPENAI_API_KEY=sk-...",
            "",
            "# Channels",
            channels.telegram && channels.telegramToken
                ? `TELEGRAM_BOT_TOKEN=${channels.telegramToken}`
                : "# TELEGRAM_BOT_TOKEN=",
            channels.discord && channels.discordToken
                ? `DISCORD_BOT_TOKEN=${channels.discordToken}`
                : "# DISCORD_BOT_TOKEN=",
            channels.slack && channels.slackToken
                ? `SLACK_BOT_TOKEN=${channels.slackToken}`
                : "# SLACK_BOT_TOKEN=",
        ];

        // ── openclaw.json config ──────────────────────────────────────────────
        const openclawJson = {
            gateway: {
                auth: { token },
                port: 3284,
            },
            providers: [
                ...(anthropicApiKey
                    ? [{ type: "anthropic", model: "claude-opus-4-5" }]
                    : []),
                ...(openaiApiKey
                    ? [{ type: "openai", model: "gpt-4o" }]
                    : []),
            ],
            channels: {
                ...(channels.telegram && channels.telegramToken
                    ? { telegram: { token: channels.telegramToken } }
                    : {}),
                ...(channels.discord && channels.discordToken
                    ? { discord: { token: channels.discordToken } }
                    : {}),
                ...(channels.slack && channels.slackToken
                    ? { slack: { botToken: channels.slackToken } }
                    : {}),
            },
        };

        // ── Ansible vars.yml (remote mode) ────────────────────────────────────
        let ansibleContent: string | null = null;
        if (mode === "remote" && ansible) {
            ansibleContent = [
                "# Ansible vars for OpenClaw deployment",
                `# Generated: ${new Date().toISOString()}`,
                "",
                `openclaw_gateway_token: "${token}"`,
                anthropicApiKey ? `anthropic_api_key: "${anthropicApiKey}"` : "# anthropic_api_key:",
                openaiApiKey ? `openai_api_key: "${openaiApiKey}"` : "# openai_api_key:",
                "",
                "openclaw_channels:",
                `  telegram: ${Boolean(channels.telegram)}`,
                `  discord: ${Boolean(channels.discord)}`,
                `  slack: ${Boolean(channels.slack)}`,
            ].join("\n");
        }

        // ── Docker compose override ───────────────────────────────────────────
        const dockerCompose = `version: '3.8'
services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3284:3284"
    env_file:
      - .env
    volumes:
      - openclaw-data:/root/.openclaw

volumes:
  openclaw-data:
`;

        return NextResponse.json({
            envFile: envLines.join("\n"),
            openclawJson: JSON.stringify(openclawJson, null, 2),
            dockerCompose,
            ansibleVars: ansibleContent,
            instanceUrl,
            mode,
        });
    } catch (err) {
        console.error("[openclaw/config]", err);
        return NextResponse.json({ error: "Failed to generate config" }, { status: 500 });
    }
}
